### ISSUE TITLE
Unable to open port 30080

### ISSUE THREAD

**Issue by shathaalzhrani** [Ahmad-Faqehi/Drupal-PostgreSQL-Kubernetes#1]
i have issue when i run command :
 kubectl apply -f drupal-deployment.yaml 
I got this warning:
The Service "drupal" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'

**Comment by Ahmad-Faqehi** [comment]
The problem is nodePort forbidden in service of drupal deployment. So I suggest to use Load Balancer as type for service. Add 
```type: LoadBalancer```
In drupal-deployment.yaml file in line 52
